# Generated by Django 4.1.10 on 2023-08-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='received', max_length=20)),
                ('dishes', models.ManyToManyField(to='dish.dishes')),
            ],
        ),
    ]
